<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MainCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('main_categories')->insert([
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 1,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 2,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],

            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 3,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 4,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 5,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 6,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 7,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 8,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 9,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 10,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 11,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 12,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 13,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 14,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 15,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 16,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 17,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 18,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 19,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 20,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],

            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 21,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 22,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 23,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 24,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 25,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 26,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],

            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 27,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 28,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],

            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 29,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 30,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 31,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 32,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],


            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Farming",
                "name_ar" => "Farming",
                "name_tur" => "Farming",
                "name_ch" => "Farming",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Cereal",
                "name_ar" => "Cereal",
                "name_tur" => "Cereal",
                "name_ch" => "Cereal",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Animal Husbandry",
                "name_ar" => "Animal Husbandry",
                "name_tur" => "Animal Husbandry",
                "name_ch" => "Animal Husbandry",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
            [
                "name_en" => "Food & Beverage",
                "name_ar" => "Food & Beverage",
                "name_tur" => "Food & Beverage",
                "name_ch" => "Food & Beverage",
                "root_category_id" => 33,
                "created_by" => "Admin",
                "updated_by" => "Admin",
            ],
        ]);
    }
}
